version: '3.3'
services:
  webapp-ts-template-api:
    build: ./server
    image: webapp-ts-template-api
    environment:
      - NODE_ENV=docker
      - PROD_ENV=production
    depends_on:
      - mongo
    stdin_open: true
    tty: true    
  webapp-ts-tempalte-client:
    build: ./client
    image: webapp-ts-tempalte-client
    depends_on:
      - webapp-ts-template-api
    stdin_open: true
    tty: true  
  mongo:
    image: mongo:latest
    stdin_open: true
    tty: true
    volumes:
      - mongo-data:/data/webapp-ts-template
volumes:
  mongo-data:
    driver: local  