version: '3.3'
services:
  server:
    image: node:lts
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    environment:
      - NODE_ENV=docker
    volumes:
      - ./server:/workspace
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity 
  
  client:
    image: node:lts
    stdin_open: true
    tty: true
    depends_on:
      - server  
    volumes:
      - ./client:/workspace
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity    
  
  mongo:
    image: mongo:latest
    stdin_open: true
    tty: true
    volumes:
      - mongo-data:/data/webapp-template-ts-db

volumes:
  mongo-data:
    driver: local