version: '3.9'
services:
  web-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: web-client
    depends_on:
      -  api-server
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_DOCKER_MODE=DOCKER_PROD
    networks:
      - webapp-ts-template-network
    ports:
      - "80:80"
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: api-server
    environment:
      - NODE_ENV=docker
      - MODE_ENV=docker_prod
    depends_on:
      - mongo
    stdin_open: true
    tty: true
    networks:
      - webapp-ts-template-network
    ports:
      - "1337:1337"          
  mongo:
    image: mongo:latest
    stdin_open: true
    tty: true
    ports:
      - "27017:27017"
    networks:
      - webapp-ts-template-network      
    volumes:
      - mongo-data:/data/webapp-ts-template
networks:
  webapp-ts-template-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local  